Li/no_std support: hashmap to btreeset
keep-starknet-strange/blockifier pull request #11
Opened 2023-08-18 13:12 UTC by lana-shanghai

#BugFix

`HashMap` can be unpredictable when we encode/decode it within the Substrate runtime, so to always get the same order and result, we convert it to `BTreeMap` and then encode. 

Solves 1 out of 4 in [issue](https://github.com/keep-starknet-strange/madara/issues/907)

2023-08-18 13:18 UTC, tdelabro requested changes
Is there no `Decode` implementation?

2023-08-18 13:18 UTC, tdelabro commented on crates/blockifier/src/execution/contract_class.rs
> +) -> BTreeMap<EntryPointType, BTreeSet<EntryPoint>> {
I think you can keep it stored as a Vec. No need to make it a BTreeSet internaly

2023-08-18 13:18 UTC, tdelabro commented on crates/blockifier/src/execution/contract_class.rs
> +            entry_point_btree.into_iter().collect::<Vec<(EntryPointType, Vec<EntryPointV1>)>>();
I don't think you need to do hashmap -> btree -> vec -> encode, you can do hashmap -> btree -> encode

2023-08-21 09:59 UTC, tdelabro requested changes

2023-08-21 09:59 UTC, tdelabro commented on crates/blockifier/src/execution/contract_class.rs
> +
Don't create two functions for this. Just write `hashmap.into_iter().collect()` directly in the original function body

2023-08-21 09:59 UTC, tdelabro commented on crates/blockifier/src/execution/contract_class.rs
> +            <HashMap<EntryPointType, Vec<EntryPoint>>>::from_iter(entry_point_btree);
Not sure about this. If you converted it to a btree before encoding, decode it as a btree too. Not as as `Vec<(EntryPointType, Vec<EntryPoint>)>`.
And then you just have to iterate once and collect into a `HashMap`

2023-08-21 09:59 UTC, tdelabro commented on crates/blockifier/src/execution/contract_class.rs
> +        let hints = <HashMap<String, Hint>>::from_iter(res.2);
Same here. Decode to Btree and iter only once

2023-08-30 12:54 UTC, tdelabro requested changes

2023-08-30 12:54 UTC, tdelabro commented on crates/blockifier/src/execution/contract_class.rs
> +        let entry_point_btree = <BTreeMap<EntryPointType, Vec<EntryPoint>>>::from_iter(res.1);
This is not needed.
On l162 decode into a `<BTreeMap<EntryPointType, Vec<EntryPoint>>>` directly. And then you only have to iterate once in order to collect into the final hashmap

2023-08-30 13:26 UTC, merged

2023-08-31 05:32 UTC, shramee commented
Hi guys,
This PR removes `spin` but it's still in use in `blockifier::sync`.

Perhaps we should test with `--no-default-features` in CI?

![image](https://github.com/keep-starknet-strange/blockifier/assets/11048263/01f6ebdc-8133-444f-af89-722b13b11d9a)